name: En Çok Aratılanlar
title: En Çok Aratılanlar
description: en çok aratılan ünlüler, en çok merak edilen ünlüler, google türkiye'de bu hafta çok aratılanlar
markdown: kramdown
highlighter: rouge
plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed', 'jekyll-sitemap']
paginate: 9
logo: logo.png
twitter: https://twitter.com/nearanmis
facebook: https://www.facebook.com/nearanmis
google_analytics: 'UA-142198871-1'

google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: