name: En Çok Aratılanlar
title: En Çok Aratılanlar
description: en çok aratılan ünlüler, en çok merak edilen ünlüler, google türkiye'de bu hafta çok aratılanlar
markdown: kramdown
highlighter: rouge
plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed', 'jekyll-sitemap']
paginate: 10
logo: logo.png
# twitter: https://twitter.com/yarismaedebiyat
# facebook: https://www.facebook.com/yarismaedebiyat
# google_analytics: 'UA-122320408-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: